trailofbits/necessist

cargo-necessist/src/lib.rs
Add option to skip `break` and `continue` statements.
=> Add `--skip-controls` option

Cargo.toml, README.md, core/src/framework/impls/rust/visitor.rs, core/tests/ci_is/enabled.rs
And partially revert 62993ac848985d5b024f2248781587a242de8625
=> Adjust Dylint metadata

.github/workflows/ci.yml, core/src/backup.rs, core/tests/ci_is/enabled.rs
https://github.com/rust-lang/rust-clippy/issues/10264 was fixed by https://github.com/rust-lang/rust-clippy/pull/10391.
Use nightly Clippy to get the fix.
=> Use nightly Clippy

core/src/core.rs
=> Update progress bar when dry run fails

core/src/framework/impls/rust/mod.rs, core/tests/ci_is/enabled.rs, scripts/clippy.sh
Also, fix bug introduced by #214
=> Run Clippy with `--warn=clippy::pedantic` in CI

README.md, core/src/cli.rs, core/src/core.rs, core/src/framework/impls/hardhat_ts/mod.rs, core/src/framework/impls/rust/mod.rs, necessist/src/framework/impls/foundry/mod.rs
=> Allow additional arguments to be passed to test commands

README.md
Added the system requirements section and mentioned two packages that were not available on my machine. We may need to try to install it on a clean machine to find all the requirements. We can wait for this exercise or we can merge this PR and add more requirements as we find them.
=> Add system requirements section in readme

core/src/core.rs, core/src/framework/auto.rs, core/src/framework/mod.rs, frameworks/src/foundry/mod.rs, frameworks/src/golang/mod.rs, frameworks/src/hardhat_ts/mod.rs, frameworks/src/lib.rs, frameworks/src/rust/mod.rs
=> Make `--framework` a command instead of a suggestion

frameworks/src/foundry/mod.rs, frameworks/src/golang/mod.rs, frameworks/src/hardhat_ts/mod.rs, frameworks/src/lib.rs, frameworks/src/rust/mod.rs
Do not merge until we have better tests.
We need a way to ensure these changes preserve existing behavior.
=> First steps toward reducing code duplication among the backends

.github/workflows/ci.yml
Until https://github.com/foundry-rs/foundry/issues/4835 is resolved.
=> Pin Foundry version

necessist/tests/ci.rs
Improve the output of tests that try to "preserve cleanliness."
=> Improve "dirty" output

necessist/tests/third_party.rs
=> Add rustdoc comments to third-party `Test` fields

core/src/core.rs, core/src/sqlite.rs, necessist/tests/necessist_db_absent/basic_reset_warn.stderr, necessist/tests/necessist_db_absent/basic_resume_warn.stderr, scripts/clippy.sh
This should reduce the number of `--reset or --resume` messages a user is presented with.
=> Initialize Sqlite database lazily

Cargo.lock, frameworks/Cargo.toml, frameworks/assets/pt.rs, frameworks/build.rs, frameworks/src/foundry/mod.rs
And check it in a test, rather than download it when building.
=> Store static pt.rs

docs/go_call_graph.dot, frameworks/src/go/visitor.rs
Continuaton of #643
The visitor is still complicated, but less so.
=> Simplify Go visitor

necessist/tests/ci.rs
=> Remove outdated comment

core/src/lib.rs, core/src/rewriter.rs, frameworks/src/go/mod.rs, necessist/tests/third_party_tests/0/go_src_mime.stdout, necessist/tests/third_party_tests/1/minio.stdout
=> Properly convert `tree-sitter` `Point`s to `LineColumn`s

backends/build/main.rs
=> Fix `rerun-if-changed` instructions

backends/src/anchor/mod.rs, backends/src/foundry/mod.rs, backends/src/foundry/visitor/mod.rs, backends/src/generic_visitor.rs, backends/src/go/mod.rs, backends/src/go/visitor.rs, backends/src/hardhat/mod.rs, backends/src/parsing.rs, backends/src/rust/mod.rs, backends/src/rust/visitor.rs, backends/src/ts/mocha/mod.rs, backends/src/ts/mocha/visitor.rs, core/src/core.rs, core/src/framework/mod.rs, necessist/tests/third_party_tests/0/chainlink_hardhat.with_config.stdout, necessist/tests/third_party_tests/0/chainlink_hardhat.without_config.stdout, necessist/tests/third_party_tests/0/operator-filter-registry.without_config.stdout, necessist/tests/third_party_tests/0/uniswap_v3-core.with_config.stdout, necessist/tests/third_party_tests/0/uniswap_v3-core.without_config.stdout, necessist/tests/third_party_tests/1/seaport.with_config.stdout, necessist/tests/third_party_tests/1/seaport.without_config.stdout
It now maps a `Span` to the set of tests that exercise it.
=> Invert `TestSpanMaps`

backends/src/rust/visitor.rs, necessist/tests/third_party_tests/0/crates_io.stdout
=> Adjust `Failed to determine module path...` warnings

necessist/tests/ci.rs
I am no longer convinced it provides value.
=> Remove `update` test

backends/src/ts/mocha/mod.rs
=> Use `swc_common::Loc`'s `col` rather than `col_display` field

necessist/tests/ci.rs
=> Remove version pinning for markdown-link-check
